#### For initializing the app
####
### Bed Capacities
# ICU
M: 50
M_Max: 3000
M_occupied: 12
icucapramp1: 10
icucapramp2: 20

# Floor
L: 100
L_Max: 15000
L_occupied: 12
floorcapramp1: 10
floorcapramp2: 20

##### Time Horizon

T_Max: 60
T: 30

##### Scenarios
# Cases per day
I_init: 50
I_initmax: 1000
I_final: 1000
I_finalmax: 3000
doublingtime: 14
doublingtime_min: 2
doublingtime_max: 28
rampslope: 1.2
rampslope_min: 0
rampslope_max: 5
rampslope_step: 0.1

##### Discharge Rates
# App initializations:
avgfloordischargetime: 7
avgicudischargetime: 10
maxfloordischargetime: 25
maxicudischargetime: 25

##### Triage Percentages
# MS: Mild Symptoms, C:ICU, F: Floor
# Ages: 0-18
percentage_MS1: 0.984
percentage_C1: 0.0
percentage_F1: 0.016
# Ages: 18-65
percentage_MS2: 0.725
percentage_C2: 0.058
percentage_F2: 0.217
# Ages: 65+
percentage_MS3: 0.425
percentage_C3: 0.163
percentage_F3: 0.412

# Average time to triage in days (currently, undifferentiated by age)
t_Triage: 0.125


##### Outcomes (percentages)
#####
#####
#  In the ICU (death or step-down)
# Ages: 0-18
p_death_ICU1: 0.0
# Ages: 18-65
p_death_ICU2: 0.1
# Ages: 65+
p_death_ICU3: 0.3

#  On the Floor (death or step-up or discharge)
# Ages: 0-18
p_death_Floor1: 0
p_stepup_Floor1: 0.1
# Ages: 18-65
p_death_Floor2: .134
p_stepup_Floor2: 0.1
# Ages: 65+
p_death_Floor3: .134
p_stepup_Floor3: 0.1

#  In the ICU Queue (death or to the ICU if empty)
# Ages: 0-18
p_toicu1: 0.5
# Ages: 18-65
p_toicu2: 0.5
# Ages: 65+
p_toicu3: 0.5

#  In the Floor Queue (death or step-up or discharge or to floor if empty)
# Ages: 0-18
p_death_WF1: 0.0
p_stepup_WF1: 0.1
p_tofloor1: 0.9 # if empty

# Ages: 18-65
p_death_WF2: .134
p_stepup_WF2: 0.1
p_tofloor2: 0.9 # if empty

# Ages: 65+
p_death_WF3: .134
p_stepup_WF3: 0.1
p_tofloor3: 0.9 # if empty

#  Post discharge from ED (death or return or recovery)
# Ages: 0-18
p_return_MS1: 0.15
p_death_MS1: 0.0066

# Ages: 18-65
p_return_MS2: 0.15
p_death_MS2: 0.0066

# Ages: 65+
p_return_MS3: 0.15
p_death_MS3: 0.0066

### Average Lengths of Stay (days)
###
###
#  In ICU
# Ages: 0-18
avg_LOS_ICU1: 10

# Ages: 18-65
avg_LOS_ICU2: 10

# Ages: 65+
avg_LOS_ICU3: 10

#  On the floor
# Ages: 0-18
avg_LOS_Floor1: 7

# Ages: 18-65
avg_LOS_Floor2: 7

# Ages: 65+
avg_LOS_Floor3: 7

#  In the floor queue if no floor bed is available throughout
# Ages: 0-18
avg_LOS_FloorQ1: 7

# Ages: 18-65
avg_LOS_FloorQ2: 7

# Ages: 65+
avg_LOS_FloorQ3: 7

#  In the ICU queue if no ICU bed is available throughout
# Ages: 0-18
avg_timetodeath_CQ1: 0.04

# Ages: 18-65
avg_timetodeath_CQ2: 0.04

# Ages: 65+
avg_timetodeath_CQ3: 0.04


#  Post-discharge from ED to resolution (return, death, or recovery)
# Ages: 0-18
avg_T_exit1: 10

# Ages: 18-65
avg_T_exit2: 10

# Ages: 65+
avg_T_exit3: 10


####### Not Operational

# Proportion of symptomatic infectives presenting to ED
# Ages: 0-18
#p_lambda1: .106
# Ages: 18-65
#p_lambda2: .364
# Ages: 65+
#p_lambda3: .612

# Death rate of symptomatic infectives prior to presenting to the ED
#mu_I1: 0.0
#mu_I2: 0.0
#mu_I3: 0.0


# Death rate of symptomatic infectives at ED prior to triage
mu_P1: 0.0
mu_P2: 0.0
mu_P3: 0.0


# Expected time to recovery pre-triage
d_phi: 14

# Expected time to death pre-triage
d_mu: 12

# Expected proportion which recover without treatment
p_phi: .85
